// PerfumeHouses.com — reference entries.
// Original editorial. Independent of every house listed; no affiliation, no retail relationship.
module.exports = [

{slug:"houbigant",name:"Houbigant",country:"France",founded:1775,founder:"Jean-François Houbigant",cat:"Historic French",
 lede:"The house that invented an entire fragrance family.",
 body:["Houbigant opened in Paris in 1775, selling gloves, powders and scented sachets to an aristocratic clientele. It is among the oldest names still recognised in perfumery.",
 "Its place in history rests on Fougère Royale, released in 1882 and built around synthetic coumarin. The composition was distinct enough that perfumers named a whole family after it. The fougère became the backbone of men's fragrance for the century that followed. Quelques Fleurs, in 1912, did something comparable for the floral bouquet."],
 sig:["Fougère Royale","Quelques Fleurs","Orangers en Fleurs"]},

{slug:"floris-london",name:"Floris London",country:"United Kingdom",founded:1730,founder:"Juan Famenias Floris",cat:"Historic British",
 lede:"England's oldest perfumer, still on the street where it started.",
 body:["Juan Famenias Floris, from Menorca, opened at 89 Jermyn Street in 1730 as a barber and comb-maker. The shop is still there, still run by his descendants, which makes it one of the longest unbroken family retail lines in London.",
 "The house holds royal warrants and built its style on English restraint: clean citrus, soft florals and barbershop freshness rather than the heavier oriental work of its French contemporaries."],
 sig:["No.89","Limes","Cefiro"]},

{slug:"guerlain",name:"Guerlain",country:"France",founded:1828,founder:"Pierre-François-Pascal Guerlain",cat:"Historic French",
 lede:"Five generations of in-house perfumers, and the invention of the modern oriental.",
 body:["Guerlain opened on the rue de Rivoli in 1828 and supplied the court of Napoleon III. What set it apart was continuity: for most of two centuries the perfumer was a Guerlain, each trained by the last.",
 "Jicky, in 1889, was among the first fragrances to use synthetics as creative material rather than as imitation. Mitsouko, in 1919, defined the chypre. Shalimar, in 1925, defined the oriental, and its vanilla-and-bergamot structure is still being copied. The house signature, a soft powdery base of vanillin, tonka and iris, is known in the trade as the Guerlinade."],
 sig:["Shalimar","Mitsouko","Jicky","L'Heure Bleue"]},

{slug:"creed",name:"Creed",country:"United Kingdom / France",founded:1760,founder:"James Henry Creed",cat:"Heritage",
 lede:"A tailoring house that became a fragrance house.",
 body:["Creed presents itself as founded in London in 1760 as a tailor, moving into scent for its clients and later relocating to Paris. Independent evidence for the earliest dates is thin and some historians dispute the claim. The influence of the modern house, run by the Creed family until its sale in 2023, is not in question.",
 "Green Irish Tweed, in 1985, set a template for fresh masculine fragrance that competitors followed for decades. Aventus, launched in 2010, became one of the most imitated men's scents ever made; its smoky pineapple opening spawned an entire category of homage."],
 sig:["Aventus","Green Irish Tweed","Silver Mountain Water"]},

{slug:"caron",name:"Caron",country:"France",founded:1904,founder:"Ernest Daltroff",cat:"Historic French",
 lede:"Bold, powdery, and unfashionable in the best sense.",
 body:["Ernest Daltroff was self-taught, and it shows in the work: Caron's classics are heavier and stranger than the Parisian norm of their day. Tabac Blond, in 1919, put leather and tobacco on a woman deliberately, at a moment when that read as scandalous.",
 "The house is known for the fountains of loose powder in its Paris boutique and for a house accord built on carnation and rose. Pour Un Homme, a plain lavender-and-vanilla from 1934, has stayed in production ever since."],
 sig:["Tabac Blond","Nuit de Noël","Pour Un Homme"]},

{slug:"chanel",name:"Chanel",country:"France",founded:1921,founder:"Gabrielle Chanel with Ernest Beaux",cat:"Fashion house",
 lede:"The fragrance that made aldehydes a language.",
 body:["Chanel N°5 launched in 1921, composed by Ernest Beaux. Its heavy aldehyde overdose gave the scent an abstract shimmer that no perfume had carried before, and it remains among the best-selling fragrances in history.",
 "Chanel is one of very few fashion houses to keep both an in-house perfumer and its own jasmine and rose fields in Grasse. Jacques Polge held the role for over thirty years and was succeeded by his son Olivier. Les Exclusifs, launched in 2007, is where the house does its more experimental work."],
 sig:["N°5","Coromandel","Sycomore","Bois des Îles"]},

{slug:"jean-patou",name:"Jean Patou",country:"France",founded:1925,founder:"Jean Patou",cat:"Fashion house",
 lede:"Built the most expensive perfume in the world, on purpose, during a depression.",
 body:["The couturier Jean Patou commissioned Henri Alméras to make Joy in 1930, at the depth of the Great Depression, as a gesture to American clients who could no longer afford couture. It used an extravagant quantity of Grasse jasmine and Bulgarian rose, and was marketed frankly on cost.",
 "The fragrance arm has been absorbed and revived more than once, but the archive (Joy, 1000, Sublime) is regarded as one of the strongest in classical French perfumery."],
 sig:["Joy","1000","Sublime"]},

{slug:"lancome",name:"Lancôme",country:"France",founded:1935,founder:"Armand Petitjean",cat:"Historic French",
 lede:"Launched with five fragrances at once, at a World's Fair.",
 body:["Armand Petitjean, formerly of Coty, introduced Lancôme at the 1935 Brussels World's Fair with five fragrances released simultaneously, which was unusual for a debut.",
 "The house moved into skincare and cosmetics early and is now better known for those, but the fragrance work continued: Trésor in 1990 and La Vie est Belle in 2012 were both major commercial successes, the latter among the top-selling women's fragrances of the last two decades."],
 sig:["Trésor","La Vie est Belle","Magie Noire"]},

{slug:"dior",sortAs:"Dior Parfums Christian",name:"Parfums Christian Dior",country:"France",founded:1947,founder:"Christian Dior",cat:"Fashion house",
 lede:"Perfume launched alongside the New Look, deliberately.",
 body:["Miss Dior appeared in 1947, the same year as the New Look collection. Dior treated fragrance as part of the silhouette rather than an accessory, and the house has kept an in-house perfumer ever since: Edmond Roudnitska in the early years, François Demachy for much of the modern era, and Francis Kurkdjian since 2021.",
 "Diorissimo, Roudnitska's 1956 lily-of-the-valley, is still cited as one of the most accomplished florals ever composed. La Collection Privée houses the current experimental work."],
 sig:["Miss Dior","Diorissimo","Eau Sauvage","Fahrenheit"]},

{slug:"acqua-di-parma",name:"Acqua di Parma",country:"Italy",founded:1916,founder:"Carlo Magnani",cat:"Italian",
 lede:"One cologne, made properly, for a very long time.",
 body:["Colonia launched in Parma in 1916: Sicilian citrus over lavender and rosemary, in the yellow cylindrical box the house still uses. It became a signature of Italian tailoring and was worn on screen by much of mid-century Hollywood.",
 "The house nearly disappeared before being revived in the 1990s by a group of Italian businessmen, and was later acquired by LVMH. The Colonia range has expanded considerably, but the original remains the reference point."],
 sig:["Colonia","Colonia Intensa","Oud"]},

{slug:"diptyque",name:"Diptyque",country:"France",founded:1961,founder:"Desmond Knox-Leet, Christiane Gautrot and Yves Coueslant",cat:"Niche French",
 lede:"Three friends, a shop on Boulevard Saint-Germain, and candles first.",
 body:["Diptyque opened in 1961 as a decorative shop selling fabrics and objects. Scented candles came next, and the first fragrance, L'Eau, arrived in 1968, based on a sixteenth-century pomander recipe.",
 "The house style is literary and specific: a scent built around one remembered place or plant rather than a market segment. Philosykos is a fig tree in Greece. Tam Dao is sandalwood recalled from Vietnam."],
 sig:["Philosykos","Tam Dao","L'Ombre dans l'Eau","Do Son"]},

{slug:"lartisan-parfumeur",sortAs:"LArtisan Parfumeur",name:"L'Artisan Parfumeur",country:"France",founded:1976,founder:"Jean Laporte",cat:"Niche French",
 lede:"Arguably the first modern niche house.",
 body:["Jean Laporte, a chemist, opened L'Artisan Parfumeur in Paris in 1976 with a then-radical idea: sell perfume under its own name rather than a couturier's, in small runs, to people who wanted something unusual.",
 "Mûre et Musc, in 1978, was a commercial hit that proved the model worked. Timbuktu and Dzing!, both by Bertrand Duchaufour, are among the more admired oddities in modern perfumery. Dzing! smells deliberately of paper, sawdust and circus animals."],
 sig:["Mûre et Musc","Timbuktu","Dzing!","Passage d'Enfer"]},

{slug:"amouage",name:"Amouage",country:"Oman",founded:1983,founder:"Established by royal decree, Sultanate of Oman",cat:"Middle East",
 lede:"Founded to revive Arabian perfumery, with no budget ceiling.",
 body:["Amouage was created in Muscat in 1983 at the instruction of the Omani royal family, with a brief to make fragrance at the highest attainable quality using Omani materials, above all silver frankincense from Dhofar.",
 "The first fragrance, Gold, was composed by Guy Robert, who described the brief as the most generous he had ever received. The house sits where Arabian and European traditions meet: Western structure carrying Arabian raw-material density. Creative direction under Christopher Chong from 2007 pushed it toward narrative, conceptual work."],
 sig:["Gold","Interlude Man","Reflection Man","Jubilation XXV"]},

{slug:"swiss-arabian",name:"Swiss Arabian",country:"United Arab Emirates",founded:1974,founder:"Hussein Adam Ali",cat:"Middle East",
 lede:"The oldest perfume house in the Emirates.",
 body:["Founded in Sharjah in 1974, Swiss Arabian was the first perfume manufacturer of any scale in the UAE, and built its reputation on oud, musk and amber attars at a time when the Gulf market was served almost entirely by imports.",
 "The house maintains both a traditional Arabian line of concentrated oils and bakhoor and a Western-style spray range. Shaghaf Oud is among its widest-known modern releases."],
 sig:["Shaghaf Oud","Casablanca","Layali Rouge"]},

{slug:"ajmal",name:"Ajmal Perfumes",country:"United Arab Emirates",founded:1951,founder:"Haji Ajmal Ali",cat:"Middle East",
 lede:"From sourcing raw oud to running its own plantations.",
 body:["Ajmal began in 1951 with the trade in agarwood itself rather than finished perfume, and that vertical position (sourcing, distilling and blending in-house) still defines it. The company operates its own agarwood plantations and distillation facilities.",
 "Its catalogue runs from traditional dehn al oud, sold by weight to connoisseurs, through to conventional retail sprays, which makes it one of the few houses fluent in both markets."],
 sig:["Dahn Al Oudh","Aurum","Wisal"]},

{slug:"rasasi",name:"Rasasi",country:"United Arab Emirates",founded:1979,founder:"Sheikh Abdul Hussain Rasasi",cat:"Middle East",
 lede:"Gulf perfumery built for a mass audience.",
 body:["Rasasi was established in Dubai in 1979 and grew into one of the largest fragrance manufacturers in the Middle East, with a catalogue running to hundreds of releases.",
 "Its commercial strength is pitch: recognisably Arabian compositions of oud, rose, saffron and amber, priced well below European niche, which has made it a common entry point for Western buyers discovering the category."],
 sig:["Hawas","La Yuqawam","Shuhrah"]},

{slug:"lattafa",name:"Lattafa Perfumes",country:"United Arab Emirates",founded:1980,founder:"Lattafa Perfumes",cat:"Middle East",
 lede:"The house that took Arabian perfumery global on price.",
 body:["Based in Sharjah, Lattafa spent decades as a regional manufacturer before a sharp rise in international visibility through the 2020s, driven largely by online fragrance communities.",
 "The model is straightforward and effective: compositions in the style of far more expensive niche releases, at a fraction of the cost. Khamrah and Asad became reference points for how quickly a Gulf house can now reach a Western audience without a Western distributor."],
 sig:["Khamrah","Asad","Fakhar","Yara"]},

{slug:"serge-lutens",name:"Serge Lutens",country:"France",founded:1992,founder:"Serge Lutens",cat:"Niche French",
 lede:"Perfume as autobiography, usually in a dark room.",
 body:["Serge Lutens came from image-making, first Dior makeup and then Shiseido, before launching fragrance under his own name in 1992 at Les Salons du Palais Royal in Paris. Nearly all of the work is composed with Christopher Sheldrake.",
 "The house made candied, resinous orientals fashionable again. Féminité du Bois built an entire style on cedar and plum; Ambre Sultan is a reference amber. Lutens writes his own copy, which is as idiosyncratic as the perfumes."],
 sig:["Ambre Sultan","Féminité du Bois","Chergui","Fille en Aiguilles"]},

{slug:"jo-malone-london",name:"Jo Malone London",country:"United Kingdom",founded:1994,founder:"Jo Malone",cat:"British",
 lede:"Made layering a mainstream idea.",
 body:["Jo Malone began blending scents for facial-treatment clients in London and opened her first shop in 1994. The proposition was new to the mass market: bright single-idea colognes, sold with the explicit suggestion that you wear two at once.",
 "The house was acquired by Estée Lauder in 1999. Its cream-and-black packaging and restrained citrus-and-flower vocabulary have been very widely imitated. Jo Malone herself later founded a separate house, Jo Loves."],
 sig:["Lime Basil & Mandarin","Wood Sage & Sea Salt","English Pear & Freesia"]},

{slug:"frederic-malle",name:"Editions de Parfums Frédéric Malle",country:"France",founded:2000,founder:"Frédéric Malle",cat:"Niche French",
 lede:"Put the perfumer's name on the bottle, like a publisher.",
 body:["Frédéric Malle, whose grandfather founded Parfums Christian Dior, launched Editions de Parfums in 2000 on an editorial model: he commissions perfumers, gives them no cost ceiling and no marketing brief, and credits them by name on the label.",
 "That single decision changed the industry's culture. Perfumers who had worked anonymously for decades, Dominique Ropion, Jean-Claude Ellena and Maurice Roucel among them, became publicly known. Portrait of a Lady and Musc Ravageur are the best-known results."],
 sig:["Portrait of a Lady","Musc Ravageur","Carnal Flower","French Lover"]},

{slug:"ormonde-jayne",name:"Ormonde Jayne",country:"United Kingdom",founded:2002,founder:"Linda Pilkington",cat:"British",
 lede:"London niche built on unusual raw materials.",
 body:["Linda Pilkington founded Ormonde Jayne in London in 2002, working with the perfumer Geza Schoen. The house is known for sourcing materials that were uncommon in Western perfumery at the time.",
 "Ormonde Woman is its signature: a dark, resinous composition built around black hemlock absolute, which almost no other house uses. The line has stayed small and independent, sold largely through its own boutiques."],
 sig:["Ormonde Woman","Ta'if","Tolu"]},

{slug:"xerjoff",name:"Xerjoff",country:"Italy",founded:2003,founder:"Sergio Momo",cat:"Italian",
 lede:"Turin luxury, with the bottle treated as an object.",
 body:["Sergio Momo founded Xerjoff in Turin, building the house around expensive naturals and elaborate presentation: Murano glass, gold, lacquer. It sits firmly at the top of the niche price bracket.",
 "The catalogue is unusually broad, spanning classical-leaning collections, an oud-focused Oud Stars line, and the accessible Casamorati range. Naxos and Erba Pura are the widest-known modern releases."],
 sig:["Naxos","Erba Pura","Alexandria II","Torino22"]},

{slug:"etat-libre-dorange",name:"Etat Libre d'Orange",country:"France",founded:2006,founder:"Etienne de Swardt",cat:"Niche French",
 lede:"Provocation as a house style, executed seriously.",
 body:["Etat Libre d'Orange launched in Paris in 2006 with names and concepts designed to unsettle the category. The provocation is real, but it sits on genuinely well-made compositions from respected perfumers.",
 "Sécrétions Magnifiques is the most notorious fragrance of the modern era. It is meant to be unpleasant. Others in the line, such as Jasmin et Cigarette and Rossy de Palma, are straightforwardly beautiful."],
 sig:["Jasmin et Cigarette","Sécrétions Magnifiques","Rossy de Palma"]},

{slug:"byredo",name:"Byredo",country:"Sweden",founded:2006,founder:"Ben Gorham",cat:"Scandinavian",
 lede:"Scandinavian minimalism applied to fragrance retail.",
 body:["Ben Gorham, a former basketball player with no perfumery training, founded Byredo in Stockholm in 2006 and worked from the start with the perfumers Olivia Giacobetti and Jérôme Epinette.",
 "The house's contribution was as much visual as olfactory: stripped packaging, plain typography and a gallery-like retail environment that much of the industry subsequently copied. Gypsy Water and Bal d'Afrique remain its signatures. Byredo was acquired by Puig in 2022."],
 sig:["Gypsy Water","Bal d'Afrique","Mojave Ghost","Blanche"]},

{slug:"le-labo",name:"Le Labo",country:"United States",founded:2006,founder:"Fabrice Penot and Eddie Roschi",cat:"American",
 lede:"Compounded in front of you, labelled with your name.",
 body:["Two Grasse-trained former L'Oréal executives opened Le Labo in New York's Nolita in 2006. Each bottle is mixed in the shop at the moment of purchase and labelled with the buyer's name and the date. The routine has barely changed since opening.",
 "Santal 33 became one of the defining scents of the 2010s, ubiquitous enough to draw its own backlash. The house was acquired by Estée Lauder in 2014."],
 sig:["Santal 33","Rose 31","Another 13"]},

{slug:"memo-paris",name:"Memo Paris",country:"France",founded:2007,founder:"Clara and John Molloy",cat:"Niche French",
 lede:"A fragrance line organised as a travel journal.",
 body:["Clara and John Molloy founded Memo in Paris in 2007, structuring the collection around places rather than accords, with each release tied to a journey, with the bottle art following suit.",
 "The work is largely composed by Alienor Massenet. Irish Leather, built on a green leather accord, and Marfa, a vanilla-tuberose, are the best-known entries."],
 sig:["Irish Leather","Marfa","Italian Leather"]},

{slug:"parfums-de-marly",name:"Parfums de Marly",country:"France",founded:2009,founder:"Julien Sprecher",cat:"Niche French",
 lede:"Eighteenth-century court perfumery, restaged for a modern market.",
 body:["Parfums de Marly takes its name and its visual language from the Château de Marly and the perfumed court of Louis XV. The house launched in 2009 and grew quickly into one of the most commercially successful independents of the last fifteen years.",
 "Layton and Herod are its anchors: sweet, heavily projecting compositions pitched precisely at the gap between designer accessibility and niche price. The house shares ownership with Initio."],
 sig:["Layton","Herod","Delina","Pegasus"]},

{slug:"maison-francis-kurkdjian",name:"Maison Francis Kurkdjian",country:"France",founded:2009,founder:"Francis Kurkdjian and Marc Chaya",cat:"Niche French",
 lede:"A star perfumer's own house, opened after two decades of hits for others.",
 body:["Francis Kurkdjian composed Le Mâle for Jean Paul Gaultier at twenty-five and spent years as one of the industry's most sought-after noses before founding his own house in Paris in 2009 with Marc Chaya.",
 "Baccarat Rouge 540, released in 2015, became one of the most influential fragrances of its decade. Its saffron-and-burnt-sugar accord has been imitated across every price tier. The house was acquired by LVMH in 2017; Kurkdjian also became in-house perfumer at Dior."],
 sig:["Baccarat Rouge 540","Grand Soir","Oud Satin Mood","Aqua Universalis"]},

{slug:"atelier-cologne",name:"Atelier Cologne",country:"France",founded:2009,founder:"Sylvie Ganter and Christophe Cervasel",cat:"Niche French",
 lede:"Rebuilt the cologne as something that lasts.",
 body:["The traditional cologne is bright and short-lived. Atelier Cologne, founded in Paris in 2009, set out to keep the citrus character but give it real persistence, using a high concentration it branded Cologne Absolue.",
 "Orange Sanguine and Clémentine California are the clearest expressions of the idea. The house was acquired by L'Oréal in 2016."],
 sig:["Orange Sanguine","Clémentine California","Vanille Insensée"]},

{slug:"nishane",name:"Nishane",country:"Turkey",founded:2012,founder:"Murat Katran and Mert Güzel",cat:"Emerging",
 lede:"Istanbul's first international niche house.",
 body:["Nishane launched in Istanbul in 2012 and became the first Turkish niche house to reach a broad international audience, distributed across Europe and the Gulf within a few years.",
 "Its strongest work draws directly on the city: Hacivat, named for a character from Turkish shadow theatre, and Ani, built on a pistachio-and-vanilla accord, are the widest-known. Extrait-strength concentration across the line is part of the house's identity."],
 sig:["Hacivat","Ani","Wulong Cha"]},

{slug:"zoologist",name:"Zoologist Perfumes",country:"Canada",founded:2013,founder:"Victor Wong",cat:"Emerging",
 lede:"One animal per fragrance, taken literally.",
 body:["Victor Wong founded Zoologist in Toronto in 2013 on a constraint that sounds like a gimmick and is not: every release interprets a single animal, and independent perfumers are commissioned and credited for each.",
 "The results are unusually adventurous. Hyrax leans into animalic hyraceum, Bat opens on damp earth and overripe fruit. The house is a good illustration of how far an independent can go when it does not have to please a retail buyer."],
 sig:["Bat","Hyrax","Chameleon"]},

{slug:"imaginary-authors",name:"Imaginary Authors",country:"United States",founded:2012,founder:"Josh Meyer",cat:"American",
 lede:"Each scent presented as the companion to a book that does not exist.",
 body:["Josh Meyer founded Imaginary Authors in Portland, Oregon, framing every release as the fragrance of a novel he invented, complete with author, jacket copy and publication date.",
 "The conceit gives the compositions room to be specific rather than commercial. Memoirs of a Trespasser is a vanilla-and-oud; A City on Fire is smoke and fig; Cape Heartache is a Pacific Northwest forest."],
 sig:["Memoirs of a Trespasser","A City on Fire","Cape Heartache"]},

{slug:"initio",name:"Initio Parfums Privés",country:"France",founded:2015,founder:"Initio Parfums Privés",cat:"Niche French",
 lede:"Built around high concentrations and heavy projection.",
 body:["Initio launched in 2015 under the same ownership as Parfums de Marly, positioned deliberately further into intensity: high extract concentrations, dense bases and unusually strong sillage.",
 "Side Effect and Oud for Greatness are its best-known releases, both trading on immediate impact rather than slow development. The marketing leans on claimed pheromone effects, which is presentation rather than chemistry."],
 sig:["Side Effect","Oud for Greatness","Rehab"]},

{slug:"bdk-parfums",name:"BDK Parfums",country:"France",founded:2016,founder:"David Benedek",cat:"Niche French",
 lede:"A young Paris house with an unusually consistent hit rate.",
 body:["David Benedek founded BDK in Paris in 2016. The house works with perfumers including Alexandra Carlin and Nathalie Lorson, and has built a reputation quickly on composition quality rather than concept.",
 "Gris Charnel (black tea, fig, sandalwood) and Rouge Smoking (cherry and almond) are the releases that established it internationally."],
 sig:["Gris Charnel","Rouge Smoking","Tubéreuse Impériale"]}

];
